-- Partners table for collaborations with organizations/federations
CREATE TABLE IF NOT EXISTS partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT NOT NULL DEFAULT '',
  website_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS but allow public access (since anon key has access)
ALTER TABLE partners ENABLE ROW LEVEL SECURITY;

-- Allow all operations with anon key (same as other tables)
CREATE POLICY "Allow all" ON partners FOR ALL USING (true) WITH CHECK (true);

-- Ensure news-images bucket exists (we already have it)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('partners-logos', 'partners-logos', true) ON CONFLICT DO NOTHING;
