ALTER TABLE rankings ADD COLUMN IF NOT EXISTS tournament TEXT DEFAULT '';
ALTER TABLE rankings ADD COLUMN IF NOT EXISTS rounds INTEGER DEFAULT 0;
ALTER TABLE rankings ADD COLUMN IF NOT EXISTS event_date DATE;
