export const countryToCode: Record<string, string> = {
  "egypt": "eg", "مصر": "eg",
  "palestine": "ps", "فلسطين": "ps",
  "jordan": "jo", "الأردن": "jo", "الاردن": "jo",
  "lebanon": "lb", "لبنان": "lb",
  "syria": "sy", "سوريا": "sy",
  "iraq": "iq", "العراق": "iq",
  "saudi arabia": "sa", "المملكة العربية السعودية": "sa", "السعودية": "sa",
  "uae": "ae", "united arab emirates": "ae", "الإمارات": "ae", "الامارات": "ae",
  "kuwait": "kw", "الكويت": "kw",
  "bahrain": "bh", "البحرين": "bh",
  "qatar": "qa", "قطر": "qa",
  "oman": "om", "عمان": "om",
  "yemen": "ye", "اليمن": "ye",
  "turkey": "tr", "تركيا": "tr",
  "usa": "us", "united states": "us", "امريكا": "us", "أمريكا": "us",
  "canada": "ca", "كندا": "ca",
  "uk": "gb", "united kingdom": "gb", "britain": "gb", "المملكة المتحدة": "gb", "بريطانيا": "gb",
  "france": "fr", "فرنسا": "fr",
  "germany": "de", "ألمانيا": "de", "المانيا": "de",
  "italy": "it", "إيطاليا": "it", "ايطاليا": "it",
  "spain": "es", "إسبانيا": "es", "اسبانيا": "es",
  "netherlands": "nl", "هولندا": "nl",
  "belgium": "be", "بلجيكا": "be",
  "switzerland": "ch", "سويسرا": "ch",
  "austria": "at", "النمسا": "at",
  "sweden": "se", "السويد": "se",
  "norway": "no", "النرويج": "no",
  "denmark": "dk", "الدنمارك": "dk",
  "finland": "fi", "فنلندا": "fi",
  "poland": "pl", "بولندا": "pl",
  "russia": "ru", "روسيا": "ru",
  "ukraine": "ua", "أوكرانيا": "ua", "اوكرانيا": "ua",
  "china": "cn", "الصين": "cn",
  "japan": "jp", "اليابان": "jp",
  "south korea": "kr", "korea": "kr", "كوريا": "kr", "كوريا الجنوبية": "kr",
  "india": "in", "الهند": "in",
  "pakistan": "pk", "باكستان": "pk",
  "bangladesh": "bd", "بنغلاديش": "bd",
  "indonesia": "id", "إندونيسيا": "id", "اندونيسيا": "id",
  "malaysia": "my", "ماليزيا": "my",
  "thailand": "th", "تايلاند": "th",
  "vietnam": "vn", "فيتنام": "vn",
  "philippines": "ph", "الفلبين": "ph",
  "australia": "au", "أستراليا": "au", "استراليا": "au",
  "new zealand": "nz", "نيوزيلندا": "nz",
  "brazil": "br", "البرازيل": "br",
  "argentina": "ar", "الأرجنتين": "ar", "الارجنتين": "ar",
  "mexico": "mx", "المكسيك": "mx",
  "colombia": "co", "كولومبيا": "co",
  "chile": "cl", "تشيلي": "cl",
  "peru": "pe", "بيرو": "pe",
  "south africa": "za", "جنوب أفريقيا": "za",
  "nigeria": "ng", "نيجيريا": "ng",
  "kenya": "ke", "كينيا": "ke",
  "morocco": "ma", "المغرب": "ma",
  "algeria": "dz", "الجزائر": "dz",
  "tunisia": "tn", "تونس": "tn",
  "libya": "ly", "ليبيا": "ly",
  "sudan": "sd", "السودان": "sd",
  "ethiopia": "et", "إثيوبيا": "et",
};

export function getFlagUrl(countryName: string): string {
  const code = countryToCode[countryName.trim().toLowerCase()];
  return code ? `https://flagcdn.com/w80/${code}.png` : "";
}
