export const countryToCode: Record<string, string> = {
  "egypt": "eg", "مصر": "eg",
  "palestine": "ps", "فلسطين": "ps",
  "jordan": "jo", "الأردن": "jo", "الاردن": "jo",
  "lebanon": "lb", "لبنان": "lb",
  "syria": "sy", "سوريا": "sy",
  "iraq": "iq", "العراق": "iq",
  "saudi arabia": "sa", "المملكة العربية السعودية": "sa", "السعودية": "sa",
  "uae": "ae", "united arab emirates": "ae", "الإمارات": "ae", "الامارات": "ae",
  "kuwait": "kw", "الكويت": "kw",
  "bahrain": "bh", "البحرين": "bh",
  "qatar": "qa", "قطر": "qa",
  "oman": "om", "عمان": "om",
  "yemen": "ye", "اليمن": "ye",
  "turkey": "tr", "تركيا": "tr",
  "usa": "us", "united states": "us", "امريكا": "us", "أمريكا": "us",
  "canada": "ca", "كندا": "ca",
  "uk": "gb", "united kingdom": "gb", "britain": "gb", "المملكة المتحدة": "gb", "بريطانيا": "gb",
  "france": "fr", "فرنسا": "fr",
  "germany": "de", "ألمانيا": "de", "المانيا": "de",
  "italy": "it", "إيطاليا": "it", "ايطاليا": "it",
  "spain": "es", "إسبانيا": "es", "اسبانيا": "es",
  "netherlands": "nl", "هولندا": "nl",
  "belgium": "be", "بلجيكا": "be",
  "switzerland": "ch", "سويسرا": "ch",
  "austria": "at", "النمسا": "at",
  "sweden": "se", "السويد": "se",
  "norway": "no", "النرويج": "no",
  "denmark": "dk", "الدنمارك": "dk",
  "finland": "fi", "فنلندا": "fi",
  "poland": "pl", "بولندا": "pl",
  "russia": "ru", "روسيا": "ru",
  "ukraine": "ua", "أوكرانيا": "ua", "اوكرانيا": "ua",
  "china": "cn", "الصين": "cn",
  "japan": "jp", "اليابان": "jp",
  "south korea": "kr", "korea": "kr", "كوريا": "kr", "كوريا الجنوبية": "kr",
  "india": "in", "الهند": "in",
  "pakistan": "pk", "باكستان": "pk",
  "bangladesh": "bd", "بنغلاديش": "bd",
  "indonesia": "id", "إندونيسيا": "id", "اندونيسيا": "id",
  "malaysia": "my", "ماليزيا": "my",
  "thailand": "th", "تايلاند": "th",
  "vietnam": "vn", "فيتنام": "vn",
  "philippines": "ph", "الفلبين": "ph",
  "australia": "au", "أستراليا": "au", "استراليا": "au",
  "new zealand": "nz", "نيوزيلندا": "nz",
  "brazil": "br", "البرازيل": "br",
  "argentina": "ar", "الأرجنتين": "ar", "الارجنتين": "ar",
  "mexico": "mx", "المكسيك": "mx",
  "colombia": "co", "كولومبيا": "co",
  "chile": "cl", "تشيلي": "cl",
  "peru": "pe", "بيرو": "pe",
  "south africa": "za", "جنوب أفريقيا": "za",
  "nigeria": "ng", "نيجيريا": "ng",
  "kenya": "ke", "كينيا": "ke",
  "morocco": "ma", "المغرب": "ma",
  "algeria": "dz", "الجزائر": "dz",
  "tunisia": "tn", "تونس": "tn",
  "libya": "ly", "ليبيا": "ly",
  "sudan": "sd", "السودان": "sd",
  "ethiopia": "et", "إثيوبيا": "et",
  "tanzania": "tz", "تنزانيا": "tz",
  "uganda": "ug", "أوغندا": "ug",
  "ghana": "gh", "غانا": "gh",
  "cameroon": "cm", "الكاميرون": "cm",
  "ivory coast": "ci", "côte d'ivoire": "ci", "ساحل العاج": "ci",
  "senegal": "sn", "السنغال": "sn",
  "zimbabwe": "zw", "زيمبابوي": "zw",
  "mozambique": "mz", "موزمبيق": "mz",
  "angola": "ao", "أنغولا": "ao",
  "dr congo": "cd", "congo": "cd", "الكونغو": "cd",
  "madagascar": "mg", "مدغشقر": "mg",
  "mauritius": "mu", "موريشيوس": "mu",
  "seychelles": "sc", "سيشل": "sc",
  "afghanistan": "af", "أفغانستان": "af",
  "iran": "ir", "إيران": "ir",
  "uzbekistan": "uz", "أوزبكستان": "uz",
  "kazakhstan": "kz", "كازاخستان": "kz",
  "azerbaijan": "az", "أذربيجان": "az",
  "georgia": "ge", "جورجيا": "ge",
  "armenia": "am", "أرمينيا": "am",
  "nepal": "np", "نيبال": "np",
  "sri lanka": "lk", "سريلانكا": "lk",
  "myanmar": "mm", "ميانمار": "mm",
  "cambodia": "kh", "كمبوديا": "kh",
  "laos": "la", "لاوس": "la",
  "mongolia": "mn", "منغوليا": "mn",
  "singapore": "sg", "سنغافورة": "sg",
  "brunei": "bn", "بروناي": "bn",
  "maldives": "mv", "جزر المالديف": "mv",
  "cyprus": "cy", "قبرص": "cy",
  "malta": "mt", "مالطا": "mt",
  "iceland": "is", "آيسلندا": "is",
  "ireland": "ie", "أيرلندا": "ie",
  "portugal": "pt", "البرتغال": "pt",
  "greece": "gr", "اليونان": "gr",
  "croatia": "hr", "كرواتيا": "hr",
  "serbia": "rs", "صربيا": "rs",
  "bulgaria": "bg", "بلغاريا": "bg",
  "romania": "ro", "رومانيا": "ro",
  "hungary": "hu", "المجر": "hu",
  "czech republic": "cz", "تشيكيا": "cz",
  "slovakia": "sk", "سلوفاكيا": "sk",
  "slovenia": "si", "سلوفينيا": "si",
  "lithuania": "lt", "ليتوانيا": "lt",
  "latvia": "lv", "لاتفيا": "lv",
  "estonia": "ee", "إستونيا": "ee",
  "albania": "al", "ألبانيا": "al",
  "macedonia": "mk", "مقدونيا": "mk", "north macedonia": "mk",
  "montenegro": "me", "الجبل الأسود": "me",
  "bosnia": "ba", "البوسنة": "ba",
  "belarus": "by", "بيلاروسيا": "by",
  "moldova": "md", "مولدوفا": "md",
  "costa rica": "cr", "كوستاريكا": "cr",
  "panama": "pa", "بنما": "pa",
  "guatemala": "gt", "غواتيمالا": "gt",
  "honduras": "hn", "هندوراس": "hn",
  "el salvador": "sv", "elsalvador": "sv", "السلفادور": "sv",
  "nicaragua": "ni", "نيكاراغوا": "ni",
  "cuba": "cu", "كوبا": "cu",
  "dominican republic": "do", "جمهورية الدومينيكان": "do",
  "puerto rico": "pr", "بورتوريكو": "pr",
  "jamaica": "jm", "جامايكا": "jm",
  "trinidad": "tt", "ترينيداد": "tt",
  "bahamas": "bs", "جزر البهاما": "bs",
  "venezuela": "ve", "فنزويلا": "ve",
  "ecuador": "ec", "الإكوادور": "ec",
  "bolivia": "bo", "بوليفيا": "bo",
  "paraguay": "py", "باراغواي": "py",
  "uruguay": "uy", "الأوروغواي": "uy",
  "guyana": "gy", "غيانا": "gy",
  "suriname": "sr", "سورينام": "sr",
  "fiji": "fj", "فيجي": "fj",
  "papua new guinea": "pg", "بابوا غينيا الجديدة": "pg",
  "samoa": "ws", "ساموا": "ws",
  "solomon islands": "sb", "جزر سليمان": "sb",
};

export function getFlagUrl(countryName: string): string {
  const code = countryToCode[countryName.trim().toLowerCase()];
  return code ? `https://flagcdn.com/w80/${code}.png` : "";
}
